### PR TITLE
#162778391 User registration

### PR DESCRIPTION
**Pull request by waracci**
What does the Pull Request do

- Create User registration views
- Create User registration tests
- How should it be manually tested?

Clone the repository using
~ `git clone https://github.com/sharkdevs/Robotics-Django.git `
-run the command `source vent/bin/activate`
Navigate to /djangorest folder
-open the terminal in that folder and start the server using `python manage.py runserver`
use `http://127.0.0.1:8000/bucketlists/auth/register` to access the registration page

Relevant pivotal tracker stories

[#162779226](https://www.pivotaltracker.com/story/show/162778391)

### CODE REVIEW

**Comment by johnwayodi** [comment]
There seems to be an issue, when I use the url _**http://127.0.0.1:8000/bucketlists/auth/register**_, I get 404 error, kindly look into that:

screen shot 2018-12-20 at 8 32 42 pm

**Review by johnwayodi — DISMISSED** [review]
Nice work,  
However, there seems to be an issue, when I use the url _**http://127.0.0.1:8000/bucketlists/auth/register**_, I get 404 error, kindly look into that:

screen shot 2018-12-20 at 8 32 42 pm

**Review by johnwayodi — COMMENTED** [review]
How did you go about testing it? I might not be approaching it correctly.

**Comment by waracci** [comment]
@johnwayodi thanks for the review, I realized that the URL `http://127.0.0.1:8000/bucketlists/auth/register` requires a trailing slash for it to work, I am currently researching on how to make the URL work without a trailing slash.

**Comment by Teatoller** [comment]
Hello Warachi,
I have followed through your PR.
The concerns I have are similar to @johnwayodi  .
I also tried to run it with the trailing slash with similar results.

Regards
Steven Ennis

**Comment by sharkdevs** [comment]
hello

> @johnwayodi thanks for the review, I realized that the URL `http://127.0.0.1:8000/bucketlists/auth/register` requires a trailing slash for it to work, I am currently researching on how to make the URL work without a trailing slash.

It is still not working with a trailing slash.. I have the error that @johnwayodi got..

**Comment by waracci** [comment]
> Hello Warachi,
> I have followed through your PR.
> The concerns I have are similar to @johnwayodi.
> I also tried to run it with the trailing slash with similar results.
> 
> Regards
> Steven Ennis

Thanks, Steve for taking your time.
I am about to push the updated code that does not require a trailing slash. 
> This is the URL to access the registration route `http://127.0.0.1:8000/auth/register/`

**Comment by waracci** [comment]
> hello
> 
> > @johnwayodi thanks for the review, I realized that the URL `http://127.0.0.1:8000/bucketlists/auth/register` requires a trailing slash for it to work, I am currently researching on how to make the URL work without a trailing slash.
> 
> It is still not working with a trailing slash.. I have the error that @johnwayodi got..

Kindly note that the URL for registration is `http://127.0.0.1:8000/auth/register/`

**Comment by sharkdevs** [comment]
> > hello
> > > @johnwayodi thanks for the review, I realized that the URL `http://127.0.0.1:8000/bucketlists/auth/register` requires a trailing slash for it to work, I am currently researching on how to make the URL work without a trailing slash.
> > 
> > 
> > It is still not working with a trailing slash.. I have the error that @johnwayodi got..
> 
> Kindly note that the URL for registration is `http://127.0.0.1:8000/auth/register/`

not working still

**Comment by waracci** [comment]
> > > hello
> > > > @johnwayodi thanks for the review, I realized that the URL `http://127.0.0.1:8000/bucketlists/auth/register` requires a trailing slash for it to work, I am currently researching on how to make the URL work without a trailing slash.
> > > 
> > > 
> > > It is still not working with a trailing slash.. I have the error that @johnwayodi got..
> > 
> > 
> > Kindly note that the URL for registration is `http://127.0.0.1:8000/auth/register/`
> 
> not working still

Okay, let me look into it. In the meantime, make sure you run migrations on your local development environment. Use the command `python manage.py migrate`

**Pull request merged**
