### PR TITLE
162803796 Robotics-Django Delete Method 

### PR DESCRIPTION
**Pull request by Teatoller**
#### What does this PR do?
* This PR creates a method that allows for deletion of individual bucketlist.
#### Description of Task to be completed?
* Write test for the bucket list DELETE method.
* Run test.
* Write algorithim to to stop test from failing.

#### How should this be manually tested?
* Create a project folder.
```
$ mkdir projects
```
* Clone the Repo: 
```
$ git clone https://github.com/sharkdevs/Robotics-Django.git 
$ git checkout ft-deletes-bucketlist-162803796

```
* Create a virtual environment.
```
$ python3 -m virtualenv env

```
* Activate the virtual environment.
```
$ source env/bin/activate
```
* Install dependencies using the 
```
$ pip install -r requirements.txt

```
* Run the server " 
```
$ cd djangorest
$ python3 manage.py runserver
```
* Open your browser on port: http://127.0.0.1:8000/bucketlists
* Adjust browser path as post http://127.0.0.1:8000/bucketlists/{id}
    NB: where id is the bucketlist id  e.g 1 or 2 ...
* Hit DELETE Button to delete the bucket list item with the id given

The screen should reflect as in the screenshot below.

#### Any background context you want to provide?
* n/a
#### Screenshots (if appropriate)

* User interface when "http://127.0.0.1:8000/bucketlists/" before creating a post.

screenshot 2018-12-21 at 06 29 30

* Create post http://127.0.0.1:8000/bucketlists/ 
(Note this screenshot is an illustration when post with id 1 was created)

screenshot 2018-12-21 at 06 40 00

*  Select post id 2 "http://127.0.0.1:8000/bucketlists/2

screenshot 2018-12-21 at 06 54 39

* Prompting to confirm deletion of post id 2

screenshot 2018-12-21 at 06 54 50

* Post id 2 successfully deleted

screenshot 2018-12-21 at 06 56 05

* Content Post id 2 can no longer be traced

screenshot 2018-12-21 at 06 55 05
#### Questions:

### CODE REVIEW

**Comment by johnwayodi** [comment]
Works fine. 
However, you appear to have a typo on the Testing section of your PR
>  Create a post and not the post "id"

Kindly look into that as it might seem confusing.

**Comment by jomasim** [comment]
**Open your browser on port: http://127.0.0.1:8000/bucketlists
Create a post and not the post "id"
Adjust browser path as post http://127.0.0.1:8000/bucketlists/ NB: where is the post id e.g 1 or 2 ...
DELETE**-These instruction are not clear. You can edit this instructions to something like this:

- Using your browser navigate to the url listed below:
```
http://127.0.0.1:8000/bucketlists/{id}
```
- The id this case refers to bucket list id for instance:

```
http://127.0.0.1:8000/bucketlists/4

```
- Hit Delete Button to delete the bucketlist item with the id given

**Comment by Teatoller** [comment]
Hello Joma,

Your feedbacks are well received and I have incorporated parts of it.

Thank you.
```
> **Open your browser on port: http://127.0.0.1:8000/bucketlists Create a post and not the post "id" Adjust browser path as post http://127.0.0.1:8000/bucketlists/ NB: where is the post id e.g 1 or 2 ... DELETE**-These instruction are not clear. You can edit this instructions to something like this:
> 
> -using your browser navigate to the url listed below:
> 
> ```
> http://127.0.0.1:8000/bucketlists/{id}
> ```
> The in this case refers to bucket list id for instance:
> 
> ```
> http://127.0.0.1:8000/bucketlists/4
> ```
> * Hit Delete Button to delete the bucketlist item with the id given

```

**Comment by Teatoller** [comment]
> Works fine.
> However, you appear to have a typo on the Trsting section of your PR
> 
> > Create a post and not the post "id"
Hello John,

I have made necessary adjustments to bring clarity in the area you highlighted.

Regards
Steven Ennis
> 
> Kindly look into that as it might seem confusing.

**Pull request merged**
