### PR TITLE
#162779276 Create Shell Structure 

### PR DESCRIPTION
**Pull request by Teatoller**
#### What does this PR do?
* Create a working shell structure for Robotics-Django application.
#### Description of Task to be completed?
* Creates a project directory.
* Creates a Git Repository.
* Creates a Virtual environment.
* Installs dependency of the virtual environment.
* Integrates DRF and API  into the 'Robotics-Django application.

#### How should this be manually tested?
* Create a project folder.
```
$ mkdir projects
```
* Clone the Repo: 
```
$ git clone https://github.com/sharkdevs/Robotics-Django.git 
$ git checkout ch-create-shell-structure-162779276

```
* Create a virtual environment.
```
$ python3 -m virtualenv env

```
* Activate the virtual environment.
```
$ source env/bin/activate
```
* Install dependencies using the 
```
$ pip install -r requirements.txt

```
* Run the server " 
```
$ cd djangorest
$ python3 manage.py runserver

```
* Open your browser on port: http://127.0.0.1:8000/

The screen should reflect as in the screenshot below.

#### Any background context you want to provide?
* n/a
#### What are the relevant pivotal tracker stories?

* https://www.pivotaltracker.com/n/projects/2233385
* id#162779276

#### Screenshots (if appropriate)
screenshot 2018-12-20 at 04 15 51

#### Questions:

### CODE REVIEW

**Comment by jomasim** [comment]
"Install dependencies using the "requirements.txt".- should instead be written as follows:
install dependencies using the command below:
```
$ pip install -r requirements.txt

```

**Comment by sharkdevs** [comment]
On the installation requirements, note that `python3 manage.py run server` cannot run from the parent folder,, One has to change directory to `/djangorest` folder before they run, else it give an error.

**Comment by Teatoller** [comment]
Hello sharkdevs,
```
> On the installation requirements, note that `python3 manage.py run server` cannot run from the parent folder,, One has to change directory to `/djangorest` folder before they run, else it give an error.
```

Thank for the clarity your feedback has brought to the PR. This has beed amended to fit.
Regards
Steven Ennis

**Comment by Teatoller** [comment]
> "Install dependencies using the "requirements.txt".- should instead be written as follows:
> install dependencies using the command below:
> 
> ```
Hello Jomasim,
```
> $ pip install -r requirements
> ```

Thank you for the input, this feed has been incorporated in amending the PR . It will enable better UX
Regards
Steven Ennis

**Comment by Paulvitalis200** [comment]
Good file directory structure

**Comment by Teatoller** [comment]
> Good file directory structure

Thank you, Paul, 
Django is a great framework.

Regards
Steven Ennis

**Pull request merged**
